/* Generated by tools/gen_icons.py from docs/mockups/hmi-ui-landscape.html. Do not edit. */
#pragma once
#include "lvgl.h"

LV_IMAGE_DECLARE(hmi_icon_home_22);
LV_IMAGE_DECLARE(hmi_icon_gauge_22);
LV_IMAGE_DECLARE(hmi_icon_warn_14);
LV_IMAGE_DECLARE(hmi_icon_warn_15);
LV_IMAGE_DECLARE(hmi_icon_warn_17);
LV_IMAGE_DECLARE(hmi_icon_warn_18);
LV_IMAGE_DECLARE(hmi_icon_warn_22);
LV_IMAGE_DECLARE(hmi_icon_list_22);
LV_IMAGE_DECLARE(hmi_icon_chip_22);
LV_IMAGE_DECLARE(hmi_icon_checkc_17);
LV_IMAGE_DECLARE(hmi_icon_checkc_22);
LV_IMAGE_DECLARE(hmi_icon_check_14);
LV_IMAGE_DECLARE(hmi_icon_check_15);
LV_IMAGE_DECLARE(hmi_icon_cross_13);
LV_IMAGE_DECLARE(hmi_icon_relay_15);
LV_IMAGE_DECLARE(hmi_icon_sensor_15);
LV_IMAGE_DECLARE(hmi_icon_link_22);
LV_IMAGE_DECLARE(hmi_icon_bolt_20);
LV_IMAGE_DECLARE(hmi_icon_wave_20);
LV_IMAGE_DECLARE(hmi_icon_power_20);
LV_IMAGE_DECLARE(hmi_icon_stop_18);
LV_IMAGE_DECLARE(hmi_icon_play_18);
LV_IMAGE_DECLARE(hmi_icon_spin_18);
LV_IMAGE_DECLARE(hmi_icon_refresh_15);
LV_IMAGE_DECLARE(hmi_icon_refresh_18);
